/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AccessController__factory } from "./AccessController__factory";
export { IAccessController__factory } from "./IAccessController__factory";
