/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as protocolRegistrySol from "./ProtocolRegistry.sol";
export type { protocolRegistrySol };
export type { IProtocolRegistry } from "./IProtocolRegistry";
export type { IVaultManagerConfig } from "./IVaultManagerConfig";
export type { VaultManagerConfig } from "./VaultManagerConfig";
