/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IStockStrategy } from "./IStockStrategy";
export type { StockStrategy } from "./StockStrategy";
