/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IPriceOracleInterface extends utils.Interface {
  functions: {
    "WETH()": FunctionFragment;
    "_addFeed(address[],address[],address[])": FunctionFragment;
    "_updateFeed(address,address,address)": FunctionFragment;
    "decimals(address,address)": FunctionFragment;
    "getEthUsdPrice(uint256)": FunctionFragment;
    "getPrice(address,address)": FunctionFragment;
    "getPriceForAmount(address,uint256,bool)": FunctionFragment;
    "getPriceForOneTokenInUSD(address)": FunctionFragment;
    "getPriceForTokenAmount(address,address,uint256)": FunctionFragment;
    "getPriceTokenUSD18Decimals(address,uint256)": FunctionFragment;
    "getPriceUSDToken(address,uint256)": FunctionFragment;
    "getUsdEthPrice(uint256)": FunctionFragment;
    "oracleExpirationThreshold()": FunctionFragment;
    "updateOracleExpirationThreshold(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "WETH"
      | "_addFeed"
      | "_updateFeed"
      | "decimals"
      | "getEthUsdPrice"
      | "getPrice"
      | "getPriceForAmount"
      | "getPriceForOneTokenInUSD"
      | "getPriceForTokenAmount"
      | "getPriceTokenUSD18Decimals"
      | "getPriceUSDToken"
      | "getUsdEthPrice"
      | "oracleExpirationThreshold"
      | "updateOracleExpirationThreshold"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_addFeed",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "_updateFeed",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "decimals",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getEthUsdPrice",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceForAmount",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceForOneTokenInUSD",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceForTokenAmount",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceTokenUSD18Decimals",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceUSDToken",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUsdEthPrice",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleExpirationThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateOracleExpirationThreshold",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_addFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_updateFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEthUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPriceForAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceForOneTokenInUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceForTokenAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceTokenUSD18Decimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceUSDToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUsdEthPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleExpirationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOracleExpirationThreshold",
    data: BytesLike
  ): Result;

  events: {
    "addFeed(address[],address[],address[])": EventFragment;
    "updateFeed(address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "addFeed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "updateFeed"): EventFragment;
}

export interface addFeedEventObject {
  base: string[];
  quote: string[];
  aggregator: string[];
}
export type addFeedEvent = TypedEvent<
  [string[], string[], string[]],
  addFeedEventObject
>;

export type addFeedEventFilter = TypedEventFilter<addFeedEvent>;

export interface updateFeedEventObject {
  base: string;
  quote: string;
  aggregator: string;
}
export type updateFeedEvent = TypedEvent<
  [string, string, string],
  updateFeedEventObject
>;

export type updateFeedEventFilter = TypedEventFilter<updateFeedEvent>;

export interface IPriceOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPriceOracleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    WETH(overrides?: CallOverrides): Promise<[string]>;

    _addFeed(
      base: PromiseOrValue<string>[],
      quote: PromiseOrValue<string>[],
      aggregator: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    _updateFeed(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      aggregator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    decimals(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getEthUsdPrice(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>;

    getPrice(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPriceForAmount(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      ethPath: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>;

    getPriceForOneTokenInUSD(
      _base: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>;

    getPriceForTokenAmount(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>;

    getPriceTokenUSD18Decimals(
      _base: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>;

    getPriceUSDToken(
      _base: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>;

    getUsdEthPrice(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>;

    oracleExpirationThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    updateOracleExpirationThreshold(
      _newTimeout: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  WETH(overrides?: CallOverrides): Promise<string>;

  _addFeed(
    base: PromiseOrValue<string>[],
    quote: PromiseOrValue<string>[],
    aggregator: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  _updateFeed(
    base: PromiseOrValue<string>,
    quote: PromiseOrValue<string>,
    aggregator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  decimals(
    base: PromiseOrValue<string>,
    quote: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<number>;

  getEthUsdPrice(
    amountIn: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPrice(
    base: PromiseOrValue<string>,
    quote: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPriceForAmount(
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    ethPath: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPriceForOneTokenInUSD(
    _base: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPriceForTokenAmount(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPriceTokenUSD18Decimals(
    _base: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPriceUSDToken(
    _base: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getUsdEthPrice(
    amountIn: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  oracleExpirationThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  updateOracleExpirationThreshold(
    _newTimeout: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    WETH(overrides?: CallOverrides): Promise<string>;

    _addFeed(
      base: PromiseOrValue<string>[],
      quote: PromiseOrValue<string>[],
      aggregator: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    _updateFeed(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      aggregator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    decimals(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<number>;

    getEthUsdPrice(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceForAmount(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      ethPath: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceForOneTokenInUSD(
      _base: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceForTokenAmount(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceTokenUSD18Decimals(
      _base: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceUSDToken(
      _base: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUsdEthPrice(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oracleExpirationThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    updateOracleExpirationThreshold(
      _newTimeout: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "addFeed(address[],address[],address[])"(
      base?: null,
      quote?: null,
      aggregator?: null
    ): addFeedEventFilter;
    addFeed(base?: null, quote?: null, aggregator?: null): addFeedEventFilter;

    "updateFeed(address,address,address)"(
      base?: null,
      quote?: null,
      aggregator?: null
    ): updateFeedEventFilter;
    updateFeed(
      base?: null,
      quote?: null,
      aggregator?: null
    ): updateFeedEventFilter;
  };

  estimateGas: {
    WETH(overrides?: CallOverrides): Promise<BigNumber>;

    _addFeed(
      base: PromiseOrValue<string>[],
      quote: PromiseOrValue<string>[],
      aggregator: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    _updateFeed(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      aggregator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    decimals(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEthUsdPrice(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrice(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceForAmount(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      ethPath: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceForOneTokenInUSD(
      _base: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceForTokenAmount(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceTokenUSD18Decimals(
      _base: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPriceUSDToken(
      _base: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUsdEthPrice(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oracleExpirationThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    updateOracleExpirationThreshold(
      _newTimeout: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    WETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _addFeed(
      base: PromiseOrValue<string>[],
      quote: PromiseOrValue<string>[],
      aggregator: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    _updateFeed(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      aggregator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    decimals(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEthUsdPrice(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrice(
      base: PromiseOrValue<string>,
      quote: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceForAmount(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      ethPath: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceForOneTokenInUSD(
      _base: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceForTokenAmount(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceTokenUSD18Decimals(
      _base: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPriceUSDToken(
      _base: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUsdEthPrice(
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracleExpirationThreshold(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateOracleExpirationThreshold(
      _newTimeout: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
