/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStockStrategy__factory } from "./IStockStrategy__factory";
export { StockStrategy__factory } from "./StockStrategy__factory";
