/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as protocolRegistrySol from "./ProtocolRegistry.sol";
export { IProtocolRegistry__factory } from "./IProtocolRegistry__factory";
export { IVaultManagerConfig__factory } from "./IVaultManagerConfig__factory";
export { VaultManagerConfig__factory } from "./VaultManagerConfig__factory";
