/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "./access";
export type { access };
import type * as registry from "./registry";
export type { registry };
import type * as strategy from "./strategy";
export type { strategy };
export type { IStrategyManager } from "./IStrategyManager";
export type { IVault } from "./IVault";
export type { StrategyManager } from "./StrategyManager";
export type { Vault } from "./Vault";
